In [14]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = [a+b+c+d for ]
answer[50]

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa20',
 'aa21',
 'aa22',
 'aa23',
 'aa24',
 'aa25',
 'aa26',
 'aa27',
 'aa28',
 'aa30',
 'aa31',
 'aa32',
 'aa33',
 'aa34',
 'aa35',
 'aa36',
 'aa37',
 'aa38',
 'aa40',
 'aa41',
 'aa42',
 'aa43',
 'aa44',
 'aa45',
 'aa46',
 'aa47',
 'aa48',
 'aa50',
 'aa51',
 'aa52',
 'aa53',
 'aa54',
 'aa55',
 'aa56',
 'aa57',
 'aa58',
 'aa60',
 'aa61',
 'aa62',
 'aa63',
 'aa64',
 'aa65',
 'aa66',
 'aa67',
 'aa68',
 'aa70',
 'aa71',
 'aa72',
 'aa73',
 'aa74',
 'aa75',
 'aa76',
 'aa77',
 'aa78',
 'aa80',
 'aa81',
 'aa82',
 'aa83',
 'aa84',
 'aa85',
 'aa86',
 'aa87',
 'aa88',
 'ab00',
 'ab01',
 'ab02',
 'ab03',
 'ab04',
 'ab05',
 'ab06',
 'ab07',
 'ab08',
 'ab10',
 'ab11',
 'ab12',
 'ab13',
 'ab14',
 'ab15',
 'ab16',
 'ab17',
 'ab18',
 'ab20',
 'ab21',
 'ab22',
 'ab23',
 'ab24',
 'ab25',
 'ab26',
 'ab27',
 'ab28',
 'ab30',
 'ab31',
 'ab32',
 

In [16]:
np = numpy
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)

NameError: name 'numpy' is not defined

In [17]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [18]:
type(lambda x: x+1)

function

In [19]:
 [x**2 for x in range(10)] 

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [20]:
np = NumPy

NameError: name 'NumPy' is not defined

In [21]:
import numpy as np


In [24]:
m = np.arange(0,50,2)

m

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [25]:
m*2
m

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [26]:
m = m*2
m


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [27]:
m = m.reshape(5,5)
m


array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

In [41]:
print (m[:,0::-2])


[[ 0]
 [20]
 [40]
 [60]
 [80]]


In [42]:
type([x**2 for x in range(10)] )

list

m=m>35
m


In [44]:
m

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

In [45]:
print(m>30)


[[False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [49]:
new = np.arange(0,36)
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [50]:
new = new.reshape(6,6)
new

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [51]:
new[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [66]:
new.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

array([[18, 20, 22],
       [30, 32, 34]])

In [65]:
np.diag(new)


array([ 0,  7, 14, 21, 28, 35])